# Generated by Django 2.0.1 on 2018-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dummy',
            field=models.CharField(default='dummy', max_length=64),
        ),
    ]
